
services:
  mongo:
    image: mongo:6
    container_name: dme-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: dme_api
    restart: always
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    env_file:
      - ./.env

  frontend:
    build: ./DME_FRONTEND
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
